version: '3.7'

services:
  postgres:
    container_name: decidim_db
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    networks:
      - decidim_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  decidim_web:
      container_name: decidim_web
      image: ${RELEASE_IMAGE:-decidim_web}
      build:
          context: .
          dockerfile: Dockerfile
      env_file: .env
      command: ["sh", "start.sh"]
      ports:
          - 3000:3000
          - 1080:1080
      networks:
          - decidim_network
      depends_on:
          - postgres
          - redis_queue
          - redis_cache

  redis_queue:
    container_name: redis_queue
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    networks:
      - decidim_network
    volumes:
      - redis_queue-data:/data

  redis_cache:
    container_name: redis_cache
    image: redis:6.0.12-alpine
    ports:
      - 6380:6379
    networks:
      - decidim_network
    volumes:
      - redis_cache-data:/data

volumes:
  redis_queue-data:
  redis_cache-data:
  postgres_data:

networks:
    decidim_network:
        driver: bridge
        name: decidim_network
